services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: shortener
      POSTGRES_PASSWORD: shortener_pass
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
